language: generic
sudo: required
dist: trusty

services:
 - docker

before_install:
 - docker pull kaelgodlike/ubuntu-trusty-qt59-aws-dev

install:
 - sh build-on-ubuntu.sh

deploy:
  provider: releases
  api_key: $GithubToken
  file: $TRAVIS_BUILD_DIR/s3util_binary.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: journeymidnight/s3util
    tags: true
