sudo: required
language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    services: docker
    before_install: docker pull kaelgodlike/ubuntu-trusty-qt59-aws-dev
    script: sh build-on-ubuntu.sh
    deploy:
      provider: releases
      api_key: $GithubToken
      file: $TRAVIS_BUILD_DIR/s3util_binary.linux.tar.gz
      file_glob: true
      skip-cleanup: true
      on:
        repo: journeymidnight/s3util
        tags: true
  - os: osx
    sudo: required
    install:
     - mkdir aws_build && cd aws_build && git clone --branch=1.6.35 --depth=1 https://github.com/aws/aws-sdk-cpp.git && cd aws-sdk-cpp && sed -i '' '/ENABLE_TESTING/s/ON/OFF/g' CMakeLists.txt && mkdir build && cd build && cmake -DBUILD_ONLY="s3" -DCMAKE_INSTALL_PREFIX="/opt" .. && make && sudo make install
     - find /opt -name *.pc
     - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/lib/pkgconfig
     - pkg-config --cflags aws-cpp-sdk-s3
     - brew install qt
    script:
     - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && /usr/local/opt/qt/bin/qmake ..
     - ls && make
     - otool -L s3util
     - install_name_tool -change /usr/local/opt/qt/lib/QtConcurrent.framework/Versions/5/QtConcurrent @executable_path/libs/QtConcurrent s3util
     - install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore @executable_path/libs/QtCore s3util
     - install_name_tool -change @rpath/libaws-cpp-sdk-s3.dylib @executable_path/libs/libaws-cpp-sdk-s3.dylib s3util
     - install_name_tool -change @rpath/libaws-cpp-sdk-core.dylib @executable_path/libs/libaws-cpp-sdk-core.dylib s3util
     - mkdir libs && cp -r /usr/local/opt/qt/lib/QtConcurrent.framework/Versions/5/QtConcurrent libs/ && cp -r /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore libs/ && cp /opt/lib/libaws-cpp-sdk-s3.dylib libs/ && cp /opt/lib/libaws-cpp-sdk-core.dylib libs/
     - otool -L libs/QtConcurrent
     - otool -L libs/QtCore
     - otool -L libs/libaws-cpp-sdk-s3.dylib
     - otool -L libs/libaws-cpp-sdk-core.dylib
     - sudo install_name_tool -id @executable_path/libs/QtConcurrent libs/QtConcurrent
     - sudo install_name_tool -id @executable_path/libs/QtCore libs/QtCore
     - sudo install_name_tool -change /usr/local/Cellar/qt/5.12.0/lib/QtCore.framework/Versions/5/QtCore @executable_path/libs/QtCore libs/QtConcurrent 
     - sudo install_name_tool -change @rpath/libaws-cpp-sdk-s3.dylib @executable_path/libs/libaws-cpp-sdk-s3.dylib libs/libaws-cpp-sdk-s3.dylib
     - sudo install_name_tool -change @rpath/libaws-cpp-sdk-core.dylib @executable_path/libs/libaws-cpp-sdk-core.dylib libs/libaws-cpp-sdk-s3.dylib
     - sudo install_name_tool -change @rpath/libaws-cpp-sdk-core.dylib @executable_path/libs/libaws-cpp-sdk-core.dylib libs/libaws-cpp-sdk-core.dylib
     - tar czvf s3util_binary.osx.tar.gz s3util libs && mv s3util_binary.osx.tar.gz $TRAVIS_BUILD_DIR/
    deploy:
      provider: releases
      api_key: $GithubToken
      file: $TRAVIS_BUILD_DIR/s3util_binary.osx.tar.gz
      file_glob: true
      skip-cleanup: true
      on:
        repo: journeymidnight/s3util
        tags: true
